  
name: Generate DB For Datasette
on:
  push:
    # paths: /data/tsv/*.tsv
    # branches:    
    # - master 

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: |
        pip3 install csvs-to-sqlite datasette
        heroku plugins:install heroku-builds

    - name: get latest file
      id: file
      run: |
        FILE=`ls data/tsv/*.tsv -Art | tail -n 1`
        echo "::set-output name=latest_file::${FILE}"

    - name: push db to heroku
      run: |
        csvs-to-sqlite "${LATEST_FILE}" covid_sql.sqlite -s $'\t'
        datasette publish heroku covid_sql.sqlite -n covid-datasette
        # git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # git config --global user.name "github-actions[bot]"
        # git add covid_sql.sqlite 
        # git commit -m'[bot] refresh sqlite db for datasette'
        # git push -f
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        LATEST_FILE: ${{ steps.file.outputs.latest_file }}
